---
name: YAML Schema Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  schema_validate:
    name: Validate Schema
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: YAML Schema Validation
      run: |
        bash ./validate.sh
